services:
  api:
    build:
      context: .
      dockerfile: docker/api/Dockerfile
    container_name: sigmatech2-api
    ports:
      - "8000:8000"
    # depends_on:
    #   - db
    volumes:
      - ./api:/var/app
    working_dir: /var/app

  web:
    build:
      context: .
      dockerfile: docker/web/Dockerfile
    container_name: sigmatech2-web
    ports:
      - "3000:3000"
    volumes:
      - ./web:/var/app
    working_dir: /var/app

#   For cloning purposes only, uncomment these lines.
#   Current usage, postgresql is hosted independently outside the orchestration.

#   db:
#     image: postgres:16
#     container_name: sigmatech2-db
#     environment:
#       POSTGRES_PASSWORD: postgres
#       POSTGRES_DB: sigmatech2
#       POSTGRES_USER: sigmatech2
#     volumes:
#       - postgres_data:/var/lib/postgresql/data
#     ports:
#       - "5000:5432"

# volumes:
#   postgres_data:
