services:
  api:
    build:
      context: .
      dockerfile: docker/api/Dockerfile
    container_name: sigmatech2-api
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - ./api:/var/app
    working_dir: /var/app

  web:
    build:
      context: .
      dockerfile: docker/web/Dockerfile
    container_name: sigmatech2-web
    ports:
      - "3000:3000"
    volumes:
      - ./web:/var/app
    working_dir: /var/app

  db:
    image: mysql:8.4
    container_name: sigmatech2-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sigmatech2
      MYSQL_USER: sigmatech2
      MYSQL_PASSWORD: sigmatech2
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "5000:3306"

volumes:
  mysql_data:
